version: "3.9"
services:
  web:
    image: node:20-bookworm-slim
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm ci && npm run dev:turbo"
